[package]
name = "day10-1"
version = "0.1.0"
authors = ["Felix Geisendörfer <felix@debuggable.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
